// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVc9xDHkOzTOFJjwzd3OVZT0KDhuBdvg',
    appId: '1:501516356866:web:9fd9163a1aa62eea1bc61b',
    messagingSenderId: '501516356866',
    projectId: 'flutter-app-aditi',
    authDomain: 'flutter-app-aditi.firebaseapp.com',
    storageBucket: 'flutter-app-aditi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjN-MuuqiobAEDXh0dJIqhljP3K4ArU5M',
    appId: '1:501516356866:android:5a4da6b889d73f3a1bc61b',
    messagingSenderId: '501516356866',
    projectId: 'flutter-app-aditi',
    storageBucket: 'flutter-app-aditi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1cbhLrSd7GcNCH7hwKcTR07L-r5h9wU',
    appId: '1:501516356866:ios:a141aa76dcc3f8bf1bc61b',
    messagingSenderId: '501516356866',
    projectId: 'flutter-app-aditi',
    storageBucket: 'flutter-app-aditi.appspot.com',
    iosClientId: '501516356866-hn4sntk2sssce3i1ll1ueiard66kfs8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.aditiSainiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc1cbhLrSd7GcNCH7hwKcTR07L-r5h9wU',
    appId: '1:501516356866:ios:a141aa76dcc3f8bf1bc61b',
    messagingSenderId: '501516356866',
    projectId: 'flutter-app-aditi',
    storageBucket: 'flutter-app-aditi.appspot.com',
    iosClientId: '501516356866-hn4sntk2sssce3i1ll1ueiard66kfs8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.aditiSainiApp',
  );
}
